nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - checksum: 52ccdf7d7ba4e9d70ccfae8b4916c27415c4fe71d222a9e1d5ac5375707eb38f127bea3a6fd603e7f8f99d7ec5b0f67344c06f5f98cd15a5d8781ce9bb9c3f7a
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://raw.githubusercontent.com/wojtekmaj/yarn-plugin-nolyfill/v1.0.2/bundles/@yarnpkg/plugin-nolyfill.js"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
