export { default as Play } from './Play'
export { default as Stop } from './Stop'
export { default as Forward } from './Forward'
export { default as Redo } from './Redo'
export { default as GithubAlt } from './GithubAlt'
export { default as EyeClose } from './EyeClose'
export { default as EyeOpen } from './EyeOpen'
